<?php

use Illuminate\Database\Seeder;

class TipoarticuloTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('tipoarticulos')->insert([

        	
   ['tipo_articulo_id' => '2','dentipart' => 'BOMBA DE AGUA CHEVROLET'],
   ['tipo_articulo_id' => '3','dentipart' => 'EMPAQUE DE CULATA '],
   ['tipo_articulo_id' => '5','dentipart' => 'CORREA DE DISTRIBUCION'],
   ['tipo_articulo_id' => '10','dentipart' => 'ACEITE DE MOTOR 10W-30 [3.78 GALON] '],
   ['tipo_articulo_id' => '68','dentipart' => 'BOMBILLO ALOGENO H4 12V'],
   ['tipo_articulo_id' => '71','dentipart' => 'LIQUIDO PARA FRENOS 500 ML'],
   ['tipo_articulo_id' => '99','dentipart' => 'PASTAS DE FRENO DELANTERAS'],
   ['tipo_articulo_id' => '100','dentipart' => 'PASTAS DE FRENO DEL/TRAS'],
   ['tipo_articulo_id' => '101','dentipart' => 'PASTAS DE FRENO TRASERAS'],
   ['tipo_articulo_id' => '102','dentipart' => 'BRAZO AXIAL DE DIRECCION CHEVROLET'],
   ['tipo_articulo_id' => '103','dentipart' => 'BRAZO AXIAL DE DIRECCION MAZDA'],
   ['tipo_articulo_id' => '104','dentipart' => 'BRAZO AXIAL DE DIRECCION HIUNDAY'],
   ['tipo_articulo_id' => '105','dentipart' => ' BRAZO AXIAL DE DIRECCION NISSAN'],
   ['tipo_articulo_id' => '106','dentipart' => 'BRAZO AXIAL DE DIRECCION RENAULT'],
   ['tipo_articulo_id' => '107','dentipart' => 'TERMINAL DERECHO RENAULT'],
   ['tipo_articulo_id' => '108','dentipart' => 'TERMINAL IZQUIERDO RENAULT'],
   ['tipo_articulo_id' => '109','dentipart' => 'TERMINAL DERECHO CHEVROLET'],
   ['tipo_articulo_id' => '110','dentipart' => 'TERMINAL IZQUIERDO CHEVROLET'],
   ['tipo_articulo_id' => '111','dentipart' => 'BRAZO TIJERA CHEVROLET'],
   ['tipo_articulo_id' => '112','dentipart' => 'AMORTIGUADOR TRASERO RENAULT'],
   ['tipo_articulo_id' => '113','dentipart' => 'BOMBA DE AGUA HYUNDAI'],
   ['tipo_articulo_id' => '114','dentipart' => 'ROTULA / ESFERA INFERIOR DELANTERA DERECHA'],
   ['tipo_articulo_id' => '115','dentipart' => 'ROTULA / ESFERA INFERIOR DELANTERA IZQUIERDA'],
   ['tipo_articulo_id' => '116','dentipart' => 'RETENEDOR / BOCIN'],
   ['tipo_articulo_id' => '117','dentipart' => 'RETENEDOR / ACEITE'],
   ['tipo_articulo_id' => '118','dentipart' => 'LIQUIDO DE FRENO 946 ML'],
   ['tipo_articulo_id' => '119','dentipart' => 'BANDA DE FRENO TRASERAS'],
   ['tipo_articulo_id' => '120','dentipart' => 'LIMPIADOR DE CUERPO DE ACELERACION'],
   ['tipo_articulo_id' => '121','dentipart' => 'ROTULA / ESFERA SUPERIOR DELANTERA IZQUIERDA'],
   ['tipo_articulo_id' => '124','dentipart' => 'ROTULA / ESFERA SUPERIOR DELANTERA DERECHA'],
   ['tipo_articulo_id' => '125','dentipart' => 'ROTULA / ESFERA SUPERIOR TRASERA DERECHA'],
   ['tipo_articulo_id' => '126','dentipart' => 'ROTULA / ESFERA SUPERIOR TRASERA IZQUIERDA'],
   ['tipo_articulo_id' => '127','dentipart' => 'ROTULA / ESFERA INFERIOR DELANTERA IZQ / DER'],
   ['tipo_articulo_id' => '128','dentipart' => 'ROTULA / ESFERA SUPERIOR DELANTERA IZQ / DER'],
   ['tipo_articulo_id' => '129','dentipart' => 'ROTULA / ESFERA SUPERIOR  TRASERA IZQ / DER'],
   ['tipo_articulo_id' => '130','dentipart' => 'TAPA DE RADIADOR 13-15 LBS'],
   ['tipo_articulo_id' => '131','dentipart' => 'BANDA DE FRENO'],
   ['tipo_articulo_id' => '132','dentipart' => 'REFRIGERANTE 4 Lts / GALON'],
   ['tipo_articulo_id' => '133','dentipart' => 'BOMBA DE GASOLINA '],
   ['tipo_articulo_id' => '134','dentipart' => 'FILTRO DE ACEITE'],
   ['tipo_articulo_id' => '135','dentipart' => 'FILTRO DE AIRE'],
   ['tipo_articulo_id' => '136','dentipart' => 'LIQUIDO PARA FRENOS 350 ML'],
   ['tipo_articulo_id' => '137','dentipart' => 'FILTRO DE GASOLINA'],
   ['tipo_articulo_id' => '138','dentipart' => 'SILICONA LOCTITTE GRIS'],
   ['tipo_articulo_id' => '139','dentipart' => 'ACEITE DE MOTOR 15W-40 CJ4 SN [1/4 CUARTO]'],
   ['tipo_articulo_id' => '140','dentipart' => 'ACEITE MINERAL 20W-50 SN  [3.78 GALON]'],
   ['tipo_articulo_id' => '141','dentipart' => 'VALVULINA ESPECIAL  140'],
   ['tipo_articulo_id' => '142','dentipart' => 'ADITIVO GASOLINA'],
   ['tipo_articulo_id' => '143','dentipart' => 'POLEA ALTERNADOR'],
   ['tipo_articulo_id' => '144','dentipart' => 'CARCAZA TERMOSTATO'],
   ['tipo_articulo_id' => '145','dentipart' => 'GRASA RODAMIENTOS ESPECIAL'],
   ['tipo_articulo_id' => '146','dentipart' => 'ACEITE DE MOTOR 15W-40 CJ4 SN [3.78 GALON]'],
   ['tipo_articulo_id' => '147','dentipart' => 'ACEITE DE MOTOR 20W-50 CJ4 SN [1/4 CUARTO]'],
   ['tipo_articulo_id' => '148','dentipart' => 'ACEITE DE MOTOR 10W-30 [1/4 CUARTO]'],
   ['tipo_articulo_id' => '149','dentipart' => 'REFRIGERANTE 1/4 CUARTO'],
   ['tipo_articulo_id' => '150','dentipart' => 'BUJIA DE ENCENDIDO'],
   ['tipo_articulo_id' => '151','dentipart' => 'KIT DE CORREA DE DISTRIBUCION'],
   ['tipo_articulo_id' => '152','dentipart' => 'RODILLOS CON CUNA'],
   ['tipo_articulo_id' => '153','dentipart' => 'CORREA DE DISTRIBUCION'],
   ['tipo_articulo_id' => '154','dentipart' => 'BOBINA DE ENCENDIDO'],
   ['tipo_articulo_id' => '155','dentipart' => 'CORREA DE ACCESORIOS'],
   ['tipo_articulo_id' => '156','dentipart' => 'KIT DE EMBRAGUE'],
   ['tipo_articulo_id' => '157','dentipart' => 'CABLES PARA BUJIAS'],
   ['tipo_articulo_id' => '158','dentipart' => 'ACEITE ATF DEXRRON II [1/4 CUARTO]'],
   ['tipo_articulo_id' => '159','dentipart' => 'ACEITE DE TRANSMISION 80 W-90 [1/4 CUARTO]'],
   ['tipo_articulo_id' => '160','dentipart' => 'SOPORTE CAJA'],
   ['tipo_articulo_id' => '161','dentipart' => 'SOPORTE MOTOR'],
   ['tipo_articulo_id' => '162','dentipart' => 'ORING VITON'],
   ['tipo_articulo_id' => '163','dentipart' => 'ACESORIOS'],
   ['tipo_articulo_id' => '164','dentipart' => 'MULTIPLE DE ADMISION'],
   ['tipo_articulo_id' => '165','dentipart' => 'RODILLO COMPACTO'],
   ['tipo_articulo_id' => '166','dentipart' => 'CUNA DE RODILLO'],
   ['tipo_articulo_id' => '167','dentipart' => 'RODILLO SIN CUNA'],
   ['tipo_articulo_id' => '168','dentipart' => 'GRASA AUTOMOTRIZ'],
   ['tipo_articulo_id' => '169','dentipart' => 'ACEITE CAJA 75W90 1/4'],
   ['tipo_articulo_id' => '170','dentipart' => 'TENSOR CORREA DISTRIBUCION'],
   ['tipo_articulo_id' => '171','dentipart' => 'TAPA PLASTICA ENVASE RENAULT'],
   ['tipo_articulo_id' => '172','dentipart' => 'INJECTOR COMBUSTIBLE'],
   ['tipo_articulo_id' => '173','dentipart' => 'ACEITE SOLUBLE'],
   ['tipo_articulo_id' => '174','dentipart' => 'GRADUADOR DE FRENOS'],
   ['tipo_articulo_id' => '175','dentipart' => 'MICROFILTRO INJECTOR'],
   ['tipo_articulo_id' => '176','dentipart' => 'EMPAQUE DE TAPA VALVULAS'],
   ['tipo_articulo_id' => '177','dentipart' => 'KIT EMBRAGUE'],
   ['tipo_articulo_id' => '178','dentipart' => 'EMPAQUE DE CARTER'],
   ['tipo_articulo_id' => '179','dentipart' => 'ALEMAN '],
   ['tipo_articulo_id' => '182','dentipart' => 'LIQUIDO PARA FRENOS 1 L'],
   ['tipo_articulo_id' => '183','dentipart' => 'LIQUIDO PARA FRENOS 250 ML'],
   ['tipo_articulo_id' => '184','dentipart' => 'MOTORKOTE LITIO 3W 1 LBS'],
   ['tipo_articulo_id' => '185','dentipart' => 'TAPONES DE CULATA'],
   ['tipo_articulo_id' => '186','dentipart' => 'TERMOSTATO'],
   ['tipo_articulo_id' => '187','dentipart' => 'VALVULA IAC'],
   ['tipo_articulo_id' => '188','dentipart' => 'CAPTADOR MAGNETICO'],
   ['tipo_articulo_id' => '189','dentipart' => 'SENSOR / TROMPO HYDRAULICO'],
   ['tipo_articulo_id' => '190','dentipart' => 'SENSOR / TROMPO TEMPERATURA'],
   ['tipo_articulo_id' => '191','dentipart' => 'ACEITE MINERAL 20W-50 SN [3.31 L GALON]'],
   ['tipo_articulo_id' => '192','dentipart' => 'FUSIBLE MF-5'],
   ['tipo_articulo_id' => '193','dentipart' => 'FUSIBLE MF-10'],
   ['tipo_articulo_id' => '194','dentipart' => 'FUSIBLE MF-15'],
   ['tipo_articulo_id' => '195','dentipart' => 'FUSIBLE MF-20'],
   ['tipo_articulo_id' => '196','dentipart' => 'FUSIBLE MF-25'],
   ['tipo_articulo_id' => '197','dentipart' => 'FUSIBLE MF-30'],
   ['tipo_articulo_id' => '198','dentipart' => 'FUSIBLE MAF-30'],
   ['tipo_articulo_id' => '199','dentipart' => 'FUSIBLE MAF-40'],
   ['tipo_articulo_id' => '200','dentipart' => 'FUSIBLE MAF-60'],
   ['tipo_articulo_id' => '201','dentipart' => 'BOMBILLO ALOGENO H1 12V'],
   ['tipo_articulo_id' => '202','dentipart' => 'BOMBILLO ALOGENO H3 12V'],
   ['tipo_articulo_id' => '203','dentipart' => 'SOPORTE AMORTIGUADOR DELANTERO [MOGOLLA]'],
   ['tipo_articulo_id' => '204','dentipart' => 'TOPES DE AMORTIGUADOR'],
   ['tipo_articulo_id' => '205','dentipart' => 'BOMBILLO LED 12V MUELITA'],
   ['tipo_articulo_id' => '206','dentipart' => 'BOMBILLO DOBLE CONTACTO 12V'],
   ['tipo_articulo_id' => '207','dentipart' => 'BOMBILLO UN [1] CONTACTO 12V'],
   ['tipo_articulo_id' => '208','dentipart' => 'PUNTA DE EJE DELANTERA LADO RUEDA'],
   ['tipo_articulo_id' => '209','dentipart' => 'PUNTA DE EJE DELANTERA LADO CAJA'],
   ['tipo_articulo_id' => '210','dentipart' => 'SENSOR / OXIGENO'],
   ['tipo_articulo_id' => '211','dentipart' => 'ACEITE DE MOTOR A GAS'],
   ['tipo_articulo_id' => '212','dentipart' => 'RELAY 5 PTA 30AMP'],
   ['tipo_articulo_id' => '213','dentipart' => 'FILTRO DE GASOLINA DE CARBURADOR'],
   ['tipo_articulo_id' => '214','dentipart' => 'RETENEDOR'],
   ['tipo_articulo_id' => '215','dentipart' => 'RELAY 5 PTA 25AMP'],
   ['tipo_articulo_id' => '216','dentipart' => 'RELAY 4 PTA 16AMP'],
   ['tipo_articulo_id' => '217','dentipart' => 'ACEITE DE MOTOR 50 MONOGRADO SN [1/4 CUARTO]'],
   ['tipo_articulo_id' => '218','dentipart' => 'EMPAQUETADURA DE MOTOR'],
   ['tipo_articulo_id' => '219','dentipart' => 'GUARDAPOLVO EJE LADO  CAJA'],
   ['tipo_articulo_id' => '220','dentipart' => 'TAPA TARRO DE AGUA RENAULT'],
   ['tipo_articulo_id' => '221','dentipart' => 'GUARDAPOLVO CAJA DE DIRECCION'],
   ['tipo_articulo_id' => '222','dentipart' => 'RETENEDORES DE TAPA VALVULA'],
   ['tipo_articulo_id' => '223','dentipart' => 'EMPAQUE DE TAPA DE CAJA'],
   ['tipo_articulo_id' => '224','dentipart' => 'EMPAQUE MULTIPLE ADMISION '],
   ['tipo_articulo_id' => '225','dentipart' => 'ORING CUERPO ACELERACION'],
   ['tipo_articulo_id' => '226','dentipart' => 'RETENEDOR PROPULSOR'],
   ['tipo_articulo_id' => '227','dentipart' => 'RETENEDOR ARBOL DE LEVA'],
   ['tipo_articulo_id' => '228','dentipart' => 'ORING BOMBA DE AGUA'],
   ['tipo_articulo_id' => '229','dentipart' => 'SELLOS DE VALVULAS'],
   ['tipo_articulo_id' => '230','dentipart' => 'BOMBILLO H7 12V'],
   ['tipo_articulo_id' => '231','dentipart' => 'ARANDELA TORNILLO DE CARTER'],
   ['tipo_articulo_id' => '232','dentipart' => 'RETENEDOR TRASERO CIGUEÃ‘AL'],
   ['tipo_articulo_id' => '233','dentipart' => 'EMPAQUE BOMBA DE ACEITE '],
   ['tipo_articulo_id' => '234','dentipart' => 'SENSOR VALVULA IAC']

		]);
    }
}