<?php

use Illuminate\Database\Seeder;

class TipovehiculoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
         DB::table('tipovehiculo')->insert([
         	['idtipovehiculo' => '1','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'LUV','anovehiculo' => 'N/A','cilindraje' => '1600 CC','anovehdos' => ''],
   ['idtipovehiculo' => '2','marcavehiculo' => 'UNIVERSAL','modelovehiculo' => 'UNIVERSAL','anovehiculo' => 'UNIVERSAL','cilindraje' => 'UNIVERSAL','anovehdos' => 'UNIVERSAL'],
   ['idtipovehiculo' => '3','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'AVEO','anovehiculo' => '2005','cilindraje' => '1600 CC','anovehdos' => '2010'],
   ['idtipovehiculo' => '4','marcavehiculo' => 'NISSAN','modelovehiculo' => 'ALMERA','anovehiculo' => '1996','cilindraje' => '1600 CC','anovehdos' => '2008'],
   ['idtipovehiculo' => '5','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'ATOS','anovehiculo' => '1997','cilindraje' => '1100 CC','anovehdos' => '2008'],
   ['idtipovehiculo' => '6','marcavehiculo' => 'MAZDA','modelovehiculo' => 'CX-9 Touring AWD','anovehiculo' => '2008','cilindraje' => '3500 CC','anovehdos' => '2008'],
   ['idtipovehiculo' => '7','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'BURBUJA SAHARA','anovehiculo' => '1998','cilindraje' => '0000','anovehdos' => '2003'],
   ['idtipovehiculo' => '8','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'LAND CRUISER BURBUJA','anovehiculo' => '1999','cilindraje' => '0000','anovehdos' => '2007'],
   ['idtipovehiculo' => '9','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'PRADO','anovehiculo' => '1998','cilindraje' => '0000','anovehdos' => '2003'],
   ['idtipovehiculo' => '10','marcavehiculo' => 'KIA','modelovehiculo' => 'PREGIO','anovehiculo' => '1994','cilindraje' => '2700','anovehdos' => '2004'],
   ['idtipovehiculo' => '11','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'HILUX','anovehiculo' => '2007','cilindraje' => '00000','anovehdos' => '2007'],
   ['idtipovehiculo' => '12','marcavehiculo' => 'MAZDA','modelovehiculo' => '6','anovehiculo' => '2004','cilindraje' => '1600','anovehdos' => '2004'],
   ['idtipovehiculo' => '13','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'LANCER','anovehiculo' => '2002','cilindraje' => '1600','anovehdos' => '2004'],
   ['idtipovehiculo' => '14','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'CORSA','anovehiculo' => '1996','cilindraje' => '1600','anovehdos' => '1997'],
   ['idtipovehiculo' => '15','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'CORSA ACTIVE','anovehiculo' => '2003','cilindraje' => '1600','anovehdos' => '2003'],
   ['idtipovehiculo' => '16','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'CORSA DIESEL TAXI','anovehiculo' => '2002','cilindraje' => '1600','anovehdos' => '2002'],
   ['idtipovehiculo' => '17','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'CORSA TAXI POWER','anovehiculo' => '2000','cilindraje' => '1600','anovehdos' => '2000'],
   ['idtipovehiculo' => '18','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'CORSA WIND','anovehiculo' => '2003','cilindraje' => '1600','anovehdos' => '2003'],
   ['idtipovehiculo' => '19','marcavehiculo' => 'IVECO','modelovehiculo' => 'FIAT DAILY','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '20','marcavehiculo' => 'IVECO','modelovehiculo' => 'TURBO DAILY 40-10 EURO II','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '21','marcavehiculo' => 'IVECO','modelovehiculo' => 'TURBO DAILY 40-12 EURO II','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '22','marcavehiculo' => 'MAZDA','modelovehiculo' => 'ALEGRO','anovehiculo' => '1998','cilindraje' => '1300','anovehdos' => '1999'],
   ['idtipovehiculo' => '23','marcavehiculo' => 'MAZDA','modelovehiculo' => 'ALEGRO','anovehiculo' => '1998','cilindraje' => '1600','anovehdos' => '1999'],
   ['idtipovehiculo' => '24','marcavehiculo' => 'RENAULT','modelovehiculo' => 'LAGUNA','anovehiculo' => '1995','cilindraje' => '00000','anovehdos' => '1995'],
   ['idtipovehiculo' => '25','marcavehiculo' => 'RENAULT','modelovehiculo' => 'SCENIC','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '26','marcavehiculo' => 'FORD','modelovehiculo' => 'EXPEDITION','anovehiculo' => '1997','cilindraje' => '00000','anovehdos' => '2003'],
   ['idtipovehiculo' => '27','marcavehiculo' => 'FORD','modelovehiculo' => 'LOBO F150','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2001'],
   ['idtipovehiculo' => '28','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'MONTERO HARD TOP','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2004'],
   ['idtipovehiculo' => '29','marcavehiculo' => 'FORD','modelovehiculo' => 'ESCAPE','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2007'],
   ['idtipovehiculo' => '30','marcavehiculo' => 'JEPP','modelovehiculo' => 'GRAND CHEROKEE LIMITED','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '31','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'COROLLA','anovehiculo' => '2002','cilindraje' => '1600','anovehdos' => '2002'],
   ['idtipovehiculo' => '32','marcavehiculo' => 'NISSAN','modelovehiculo' => 'ARMADA','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2004'],
   ['idtipovehiculo' => '33','marcavehiculo' => 'NISSAN','modelovehiculo' => 'FRONTIER','anovehiculo' => '2002','cilindraje' => '00000','anovehdos' => '2004'],
   ['idtipovehiculo' => '34','marcavehiculo' => 'NISSAN','modelovehiculo' => 'QUEST','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2003'],
   ['idtipovehiculo' => '35','marcavehiculo' => 'NISSAN','modelovehiculo' => 'X-TERRA','anovehiculo' => '1999','cilindraje' => '00000','anovehdos' => '2002'],
   ['idtipovehiculo' => '36','marcavehiculo' => 'NISSAN','modelovehiculo' => 'X-TRAIL','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2004'],
   ['idtipovehiculo' => '37','marcavehiculo' => 'MAZDA','modelovehiculo' => '626','anovehiculo' => '1983','cilindraje' => '00000','anovehdos' => '1988'],
   ['idtipovehiculo' => '38','marcavehiculo' => 'KIA','modelovehiculo' => 'RIO','anovehiculo' => '2002','cilindraje' => '1300','anovehdos' => '2012'],
   ['idtipovehiculo' => '39','marcavehiculo' => 'KIA','modelovehiculo' => 'RIO','anovehiculo' => '2002','cilindraje' => '1500','anovehdos' => '2012'],
   ['idtipovehiculo' => '40','marcavehiculo' => 'VOLKSWAGEN','modelovehiculo' => 'GOLF','anovehiculo' => '2004','cilindraje' => '1.8 Lts','anovehdos' => '2005'],
   ['idtipovehiculo' => '41','marcavehiculo' => 'VOLKSWAGEN','modelovehiculo' => 'GTI MANHATTAN','anovehiculo' => '2004','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '42','marcavehiculo' => 'VOLKSWAGEN','modelovehiculo' => 'JETTA','anovehiculo' => '2004','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '43','marcavehiculo' => 'NISSAN','modelovehiculo' => 'SUNNY','anovehiculo' => '1992','cilindraje' => '00000','anovehdos' => '1992'],
   ['idtipovehiculo' => '44','marcavehiculo' => 'NISSAN','modelovehiculo' => 'VANETTE','anovehiculo' => '1991','cilindraje' => '00000','anovehdos' => '1992'],
   ['idtipovehiculo' => '45','marcavehiculo' => 'DACIA','modelovehiculo' => 'AUTO','anovehiculo' => '1990','cilindraje' => '00000','anovehdos' => '1990'],
   ['idtipovehiculo' => '46','marcavehiculo' => 'DACIA','modelovehiculo' => 'BREAK','anovehiculo' => '1990','cilindraje' => '00000','anovehdos' => '1990'],
   ['idtipovehiculo' => '47','marcavehiculo' => 'DACIA','modelovehiculo' => 'PICK-UP','anovehiculo' => '1990','cilindraje' => '00000','anovehdos' => '1990'],
   ['idtipovehiculo' => '48','marcavehiculo' => 'FIAT','modelovehiculo' => 'TEMPRA','anovehiculo' => '1996','cilindraje' => '00000','anovehdos' => '1996'],
   ['idtipovehiculo' => '49','marcavehiculo' => 'RENAULT','modelovehiculo' => 'R12','anovehiculo' => '1973','cilindraje' => '00000','anovehdos' => '1981'],
   ['idtipovehiculo' => '50','marcavehiculo' => 'RENAULT','modelovehiculo' => '4','anovehiculo' => '1985','cilindraje' => '00000','anovehdos' => '1992'],
   ['idtipovehiculo' => '51','marcavehiculo' => 'RENAULT','modelovehiculo' => '6','anovehiculo' => '1984','cilindraje' => '00000','anovehdos' => '1984'],
   ['idtipovehiculo' => '52','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'CRESSIDA','anovehiculo' => '1989','cilindraje' => '00000','anovehdos' => '1992'],
   ['idtipovehiculo' => '53','marcavehiculo' => 'CITROEN','modelovehiculo' => 'SAXO 1.7 VTR','anovehiculo' => '1994','cilindraje' => '1700','anovehdos' => '2002'],
   ['idtipovehiculo' => '54','marcavehiculo' => 'PEUGEOT','modelovehiculo' => '306 XR','anovehiculo' => '1994','cilindraje' => '1800','anovehdos' => '2002'],
   ['idtipovehiculo' => '55','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'ACCENT VISION','anovehiculo' => '2005','cilindraje' => '00000','anovehdos' => '2017'],
   ['idtipovehiculo' => '56','marcavehiculo' => 'KIA','modelovehiculo' => 'PICANTO','anovehiculo' => '2007','cilindraje' => '00000','anovehdos' => '2017'],
   ['idtipovehiculo' => '57','marcavehiculo' => 'MAZDA','modelovehiculo' => 'MATSURI','anovehiculo' => '1993','cilindraje' => '00000','anovehdos' => '1997'],
   ['idtipovehiculo' => '58','marcavehiculo' => 'KIA','modelovehiculo' => 'SPORTAGE','anovehiculo' => '2011','cilindraje' => '2.0','anovehdos' => '2011'],
   ['idtipovehiculo' => '59','marcavehiculo' => 'FORD','modelovehiculo' => 'RANGER 4X2','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2001'],
   ['idtipovehiculo' => '60','marcavehiculo' => 'MAZDA','modelovehiculo' => 'B-2200','anovehiculo' => '2001','cilindraje' => '2200','anovehdos' => '2003'],
   ['idtipovehiculo' => '61','marcavehiculo' => 'MAZDA','modelovehiculo' => 'B-2000','anovehiculo' => '2001','cilindraje' => '2.0','anovehdos' => '2003'],
   ['idtipovehiculo' => '62','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'ASTRA BRASILERO','anovehiculo' => '2002','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '63','marcavehiculo' => 'NISSAN','modelovehiculo' => 'MATRIX','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2008'],
   ['idtipovehiculo' => '64','marcavehiculo' => 'NISSAN','modelovehiculo' => 'MURANO','anovehiculo' => '2004','cilindraje' => '00000','anovehdos' => '2004'],
   ['idtipovehiculo' => '65','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'COROLLA','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2008'],
   ['idtipovehiculo' => '66','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'H1','anovehiculo' => '1997','cilindraje' => '00000','anovehdos' => '2003'],
   ['idtipovehiculo' => '67','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'STAREX','anovehiculo' => '1997','cilindraje' => '00000','anovehdos' => '2003'],
   ['idtipovehiculo' => '68','marcavehiculo' => 'JAC','modelovehiculo' => 'REFINE 2.7 TD','anovehiculo' => '2012','cilindraje' => '00000','anovehdos' => '2012'],
   ['idtipovehiculo' => '69','marcavehiculo' => 'DAIHATSU','modelovehiculo' => 'MATERIA','anovehiculo' => '2007','cilindraje' => '1.5','anovehdos' => '2011'],
   ['idtipovehiculo' => '70','marcavehiculo' => 'FORD','modelovehiculo' => 'FIESTA','anovehiculo' => '2010','cilindraje' => '1.6 LTS','anovehdos' => '2010'],
   ['idtipovehiculo' => '71','marcavehiculo' => 'MAZDA','modelovehiculo' => '2','anovehiculo' => '2008','cilindraje' => '00000','anovehdos' => '2016'],
   ['idtipovehiculo' => '72','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'ASTRA VENEZOLANO','anovehiculo' => '2005','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '73','marcavehiculo' => 'FORD','modelovehiculo' => 'FOCUS II','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2007'],
   ['idtipovehiculo' => '74','marcavehiculo' => 'MAZDA','modelovehiculo' => '3','anovehiculo' => '2004','cilindraje' => '00000','anovehdos' => '2006'],
   ['idtipovehiculo' => '75','marcavehiculo' => 'MAZDA','modelovehiculo' => '5','anovehiculo' => '2005','cilindraje' => '00000','anovehdos' => '2016'],
   ['idtipovehiculo' => '76','marcavehiculo' => 'VOLVO','modelovehiculo' => 'C70','anovehiculo' => '2006','cilindraje' => '00000','anovehdos' => '2016'],
   ['idtipovehiculo' => '77','marcavehiculo' => 'VOLVO','modelovehiculo' => 'S40','anovehiculo' => '2006','cilindraje' => '00000','anovehdos' => '2016'],
   ['idtipovehiculo' => '78','marcavehiculo' => 'VOLVO','modelovehiculo' => 'V50','anovehiculo' => '2005','cilindraje' => '00000','anovehdos' => 'ADELANTE'],
   ['idtipovehiculo' => '79','marcavehiculo' => 'RENAULT','modelovehiculo' => 'KANGOO','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '80','marcavehiculo' => 'RENAULT','modelovehiculo' => 'METROPOLY TAXI','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '81','marcavehiculo' => 'MAZDA','modelovehiculo' => 'MILENIO','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2002'],
   ['idtipovehiculo' => '82','marcavehiculo' => 'FORD','modelovehiculo' => 'LASER','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => 'ADELANTE'],
   ['idtipovehiculo' => '83','marcavehiculo' => 'MAZDA','modelovehiculo' => 'ALEGRO','anovehiculo' => '2000','cilindraje' => '1.3','anovehdos' => '2002'],
   ['idtipovehiculo' => '84','marcavehiculo' => 'MAZDA','modelovehiculo' => 'ALEGRO','anovehiculo' => '2000','cilindraje' => '1.6','anovehdos' => '2002'],
   ['idtipovehiculo' => '85','marcavehiculo' => 'FORD','modelovehiculo' => 'ADVENTURE','anovehiculo' => '1995','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '86','marcavehiculo' => 'FORD','modelovehiculo' => 'EXPLORER','anovehiculo' => '1995','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '87','marcavehiculo' => 'FORD','modelovehiculo' => 'RANGER','anovehiculo' => '1995','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '88','marcavehiculo' => 'MAZDA','modelovehiculo' => 'B-2600','anovehiculo' => '2005','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '89','marcavehiculo' => 'DAIHATSU','modelovehiculo' => 'F-20','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '90','marcavehiculo' => 'DAIHATSU','modelovehiculo' => 'FEROZA','anovehiculo' => '1991','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '91','marcavehiculo' => 'DAIHATSU','modelovehiculo' => 'ROCKY','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '92','marcavehiculo' => 'MAZDA','modelovehiculo' => 'PICK-UP B-1600','anovehiculo' => '1983','cilindraje' => '00000','anovehdos' => 'ADELANTE'],
   ['idtipovehiculo' => '93','marcavehiculo' => 'MAZDA','modelovehiculo' => 'B-2600','anovehiculo' => '1994','cilindraje' => '2.6 LTS','anovehdos' => '2000'],
   ['idtipovehiculo' => '94','marcavehiculo' => 'FORD','modelovehiculo' => 'FIESTA [DISCO VENTILADO]','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '95','marcavehiculo' => 'FORD','modelovehiculo' => 'ESCAPE','anovehiculo' => '2008','cilindraje' => '00000','anovehdos' => '2008'],
   ['idtipovehiculo' => '96','marcavehiculo' => 'KIA','modelovehiculo' => 'SEPHIA','anovehiculo' => '1994','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '97','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'SPRINT','anovehiculo' => '1997','cilindraje' => '00000','anovehdos' => '1997'],
   ['idtipovehiculo' => '98','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'BURBUJA LAND CRUISER','anovehiculo' => '1999','cilindraje' => '00000','anovehdos' => '2006'],
   ['idtipovehiculo' => '99','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'LAND CRUISER','anovehiculo' => '1992','cilindraje' => '00000','anovehdos' => '1995'],
   ['idtipovehiculo' => '100','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'PRADO','anovehiculo' => '2004','cilindraje' => '00000','anovehdos' => '2004'],
   ['idtipovehiculo' => '101','marcavehiculo' => 'TOYOTA','modelovehiculo' => 'SAMURAI','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '102','marcavehiculo' => 'NISSAN','modelovehiculo' => 'CABSTAR','anovehiculo' => '2005','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '103','marcavehiculo' => 'MAZDA','modelovehiculo' => '6','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '104','marcavehiculo' => 'RENAULT','modelovehiculo' => 'KANGOO','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => 'ADELANTE'],
   ['idtipovehiculo' => '106','marcavehiculo' => 'RENAULT','modelovehiculo' => 'MEGANE II','anovehiculo' => '2003','cilindraje' => '00000','anovehdos' => '2005'],
   ['idtipovehiculo' => '107','marcavehiculo' => 'KIA','modelovehiculo' => 'SPORTAGE','anovehiculo' => '2011','cilindraje' => '2.7 Lts','anovehdos' => '2011'],
   ['idtipovehiculo' => '108','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'TUCSON IX35','anovehiculo' => '2010','cilindraje' => '00000','anovehdos' => '2010'],
   ['idtipovehiculo' => '109','marcavehiculo' => 'FORD','modelovehiculo' => 'ECOSPORT 4WD AT','anovehiculo' => '2011','cilindraje' => '00000','anovehdos' => '2011'],
   ['idtipovehiculo' => '110','marcavehiculo' => 'MAZDA','modelovehiculo' => 'MILENIUM','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2001'],
   ['idtipovehiculo' => '111','marcavehiculo' => 'AUDI  ','modelovehiculo' => 'A3 [8L]','anovehiculo' => '1996','cilindraje' => '00000','anovehdos' => '1996'],
   ['idtipovehiculo' => '112','marcavehiculo' => 'AUDI','modelovehiculo' => 'TT','anovehiculo' => '1998','cilindraje' => '00000','anovehdos' => '1998'],
   ['idtipovehiculo' => '113','marcavehiculo' => 'SEAT','modelovehiculo' => 'LEON CUPRA','anovehiculo' => '1999','cilindraje' => '00000','anovehdos' => '1999'],
   ['idtipovehiculo' => '114','marcavehiculo' => 'VOLKSWAGEN','modelovehiculo' => 'BORA','anovehiculo' => '1998','cilindraje' => '00000','anovehdos' => '1998'],
   ['idtipovehiculo' => '115','marcavehiculo' => 'VOLKSWAGEN','modelovehiculo' => 'PASSAT','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2001'],
   ['idtipovehiculo' => '116','marcavehiculo' => 'CHANA','modelovehiculo' => 'BENNI CLASICC ','anovehiculo' => '2005','cilindraje' => '1.3 Lts','anovehdos' => '2005'],
   ['idtipovehiculo' => '117','marcavehiculo' => 'CHEVI','modelovehiculo' => 'TAXI','anovehiculo' => '1992','cilindraje' => '00000','anovehdos' => '2002'],
   ['idtipovehiculo' => '118','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'TATA INDIA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '119','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'SWIIFT','anovehiculo' => '1991','cilindraje' => '1.3 Lts','anovehdos' => '2004'],
   ['idtipovehiculo' => '120','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'GRAND VITARA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '121','marcavehiculo' => 'NISSAN','modelovehiculo' => 'URBAN','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '122','marcavehiculo' => 'NISSAN','modelovehiculo' => 'SENTRA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '123','marcavehiculo' => 'RENAULT','modelovehiculo' => '18','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '124','marcavehiculo' => 'RENAULT','modelovehiculo' => 'LOGAN','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '125','marcavehiculo' => 'RENAULT','modelovehiculo' => 'SANDERO','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '126','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'SPARK','anovehiculo' => 'TODOS','cilindraje' => '1.100 CC','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '127','marcavehiculo' => 'RENAULT','modelovehiculo' => 'CLIO FASE 1','anovehiculo' => '1998','cilindraje' => '00000','anovehdos' => '1998'],
   ['idtipovehiculo' => '128','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'C-30','anovehiculo' => '1974','cilindraje' => '00000','anovehdos' => '1975'],
   ['idtipovehiculo' => '129','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'P-30','anovehiculo' => '1974','cilindraje' => '00000','anovehdos' => '1975'],
   ['idtipovehiculo' => '130','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'LUV','anovehiculo' => '0000','cilindraje' => '2.300 CC','anovehdos' => '0000'],
   ['idtipovehiculo' => '131','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'OPTRA','anovehiculo' => '0000','cilindraje' => '1.6 CC','anovehdos' => '0000'],
   ['idtipovehiculo' => '132','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'I 10','anovehiculo' => '0000','cilindraje' => '00000','anovehdos' => '0000'],
   ['idtipovehiculo' => '133','marcavehiculo' => 'HYUNDAI','modelovehiculo' => 'KIA','anovehiculo' => '0000','cilindraje' => '00000','anovehdos' => '0000'],
   ['idtipovehiculo' => '134','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'SPARK GT','anovehiculo' => '2015','cilindraje' => '1.1','anovehdos' => '2015'],
   ['idtipovehiculo' => '135','marcavehiculo' => 'RENAULT','modelovehiculo' => 'DUSTER 1600 EXPRESION','anovehiculo' => '2010','cilindraje' => '1600','anovehdos' => '2010'],
   ['idtipovehiculo' => '136','marcavehiculo' => 'RENAULT','modelovehiculo' => 'GRANDTOUR','anovehiculo' => '...','cilindraje' => '00000','anovehdos' => '...'],
   ['idtipovehiculo' => '137','marcavehiculo' => 'RENAULT','modelovehiculo' => 'LOGAN  ESTATE','anovehiculo' => '...','cilindraje' => '1600','anovehdos' => '...'],
   ['idtipovehiculo' => '138','marcavehiculo' => 'NISSAN','modelovehiculo' => '/ NISSAN MICRA 1.4 06..09 NOTE','anovehiculo' => '2006','cilindraje' => '1400','anovehdos' => '2009'],
   ['idtipovehiculo' => '139','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'LANOS','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '140','marcavehiculo' => 'CHEVROLET','modelovehiculo' => '7:24 - CHRONOS','anovehiculo' => 'TODOS','cilindraje' => '1.0 CC','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '141','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'CHERY QQ','anovehiculo' => 'TODOS','cilindraje' => '1.0 CC','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '142','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'MATIZ','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '143','marcavehiculo' => 'RENAULT','modelovehiculo' => 'CLIO FASE II','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '144','marcavehiculo' => 'RENAULT','modelovehiculo' => 'SYMBOL','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '145','marcavehiculo' => 'RENAULT','modelovehiculo' => 'CITIUS','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '146','marcavehiculo' => 'RENAULT','modelovehiculo' => 'TWINGO','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '147','marcavehiculo' => 'LIFAN','modelovehiculo' => 'LIFAN 520','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '148','marcavehiculo' => 'RENAULT','modelovehiculo' => 'SYMBOL II','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '149','marcavehiculo' => 'MAZDA','modelovehiculo' => '323','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '150','marcavehiculo' => 'DODGE - CRYSLER','modelovehiculo' => 'DODGE I','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '151','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'CIELO','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '152','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'ESPERO','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '153','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'RACER','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '154','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'NUBIRA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '155','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'LEGANZA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '156','marcavehiculo' => 'DAEWOO','modelovehiculo' => 'TACUMA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '157','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'SAMURAI','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '158','marcavehiculo' => 'SUZUKI','modelovehiculo' => 'VITARA','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '159','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'OUTLANDER','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '160','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'SUPER CARRY','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '161','marcavehiculo' => 'CHERY','modelovehiculo' => 'VAN CARGO','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '162','marcavehiculo' => 'CHEVROLET','modelovehiculo' => 'CORSA EVOLUTION','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '163','marcavehiculo' => 'HAFFEI','modelovehiculo' => 'MINI VAN','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS'],
   ['idtipovehiculo' => '164','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'MONTERO','anovehiculo' => '1990','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '165','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'L200','anovehiculo' => '2000','cilindraje' => '00000','anovehdos' => '2000'],
   ['idtipovehiculo' => '166','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'NATIVA V6','anovehiculo' => '0000','cilindraje' => '00000','anovehdos' => '0000'],
   ['idtipovehiculo' => '167','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'MONTERO','anovehiculo' => '2001','cilindraje' => '00000','anovehdos' => '2001'],
   ['idtipovehiculo' => '168','marcavehiculo' => 'MITSUBISHI','modelovehiculo' => 'L 300','anovehiculo' => 'TODOS','cilindraje' => '00000','anovehdos' => 'TODOS']
  		]);
    }
}
